# Copyright (c) 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-creator: 'kube:admin'
    opendatahub.io/notebook-image-desc: ''
    opendatahub.io/notebook-image-name: Intel速 Optimized TensorFlow
    opendatahub.io/notebook-image-url: 'quay.io/opendatahub/workbench-images:jupyter-intel-tensorflow-ubi9-python-3.9-20240320-503090e'
    opendatahub.io/recommended-accelerators: '["gpu.intel.com/i915"]'
  name: custom-intel-tensorflow
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: jupyter-intel-tensorflow-ubi9-python-3.9-20240320-503090e
      annotations:
        opendatahub.io/notebook-software: '[{"name":"Intel速 oneAPI","version":"2024.0"},{"name":"Python","version":"v3.9"},{"name":"TensorFlow","version":"2.14"},{"name":"Intel速 Extension for TensorFlow","version":"2.14"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"TensorFlow","version":"2.14"},{"name":"Intel速 Extension for TensorFlow","version":"2.14"},{"name":"Tensorboard","version":"2.14"},{"name":"Boto3","version":"1.34"},{"name":"Kafka-Python","version":"2.0"},{"name":"Kfp-tekton","version":"1.5"},{"name":"Matplotlib","version":"3.6"},{"name":"Numpy","version":"1.26"},{"name":"Pandas","version":"1.5"},{"name":"Scikit-learn","version":"1.4"},{"name":"Scipy","version":"1.11"},{"name":"Elyra","version":"3.15"},{"name":"PyMongo","version":"4.5"},{"name":"Pyodbc","version":"4.0"}, {"name":"Codeflare-SDK","version":"0.13"}, {"name":"Sklearn-onnx","version":"1.15"}, {"name":"Psycopg","version":"3.1"}, {"name":"MySQL Connector/Python","version":"8.0"}]'
        openshift.io/imported-from: 'quay.io/opendatahub/workbench-images:jupyter-intel-tensorflow-ubi9-python-3.9-20240320-503090e'
      from:
        kind: DockerImage
        name: 'quay.io/opendatahub/workbench-images:jupyter-intel-tensorflow-ubi9-python-3.9-20240320-503090e'
      generation: 2
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
