# Copyright (c) 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  huggingface-llm:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ""
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME:-intel/intel-optimized-pytorch}
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-2.3.0-pip-multinode}
      context: charts/training/huggingface_llm
      labels:
        dependency.python.pip: requirements.txt
        docs: pytorch
        org.opencontainers.base.name: "intel/intel-optimized-pytorch:${IPEX_VERSION:-2.3.0}-pip-multinode"
        org.opencontainers.image.name: "intel/ai-workflows"
        org.opencontainers.image.title: "IntelÂ® Extension for PyTorch with Hugging Face LLM fine tuning"
        org.opencontainers.image.version: torch-${PYTORCH_VERSION:-2.3.0}-huggingface-multinode-${PYTHON_VERSION:-3.10}
    command: >
      sh -c "python /workspace/scripts/finetune.py --help"
    image: ${REGISTRY}/${REPO}:b-${GITHUB_RUN_NUMBER:-0}-torch-${PYTORCH_VERSION:-2.3.0}-huggingface-multinode-${PYTHON_VERSION:-3.10}
    pull_policy: always
