# Copyright (c) 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Merge Check
on:
  merge_group: null
permissions: read-all
jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit
      - uses: fountainhead/action-wait-for-check@5a908a24814494009c4bb27c242ea38c93c593be
        id: helm-ci
        with:
          checkName: helm-ci
          ref: ${{ github.event.merge_group.head_ref }}
          timeoutSeconds: 1800
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: fountainhead/action-wait-for-check@5a908a24814494009c4bb27c242ea38c93c593be
        if: ${{ steps.helm-ci.outputs.conclusion == 'success' }}
        id: integration-test
        with:
          checkName: integration-test
          ref: ${{ github.event.merge_group.head_ref }}
          timeoutSeconds: 1800
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: fountainhead/action-wait-for-check@5a908a24814494009c4bb27c242ea38c93c593be
        if: ${{ steps.integration-test.outputs.conclusion == 'success' }}
        id: coverage
        with:
          checkName: coverage
          ref: ${{ github.event.merge_group.head_ref }}
          timeoutSeconds: 1800
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.coverage.outputs.conclusion != 'success' }}
        run: exit 1
